# fly.toml app configuration file generated for fso-part4-bloglist-backend on 2025-10-13T12:27:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fso-part4-bloglist-backend'
primary_region = 'yyz'

[build]

[env]
  PORT = "3003" # add this


[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
